<?php

require_once 'AppController.php';
require_once __DIR__ . '/../models/User.php';
require_once __DIR__ . '/../repository/UserRepository.php';

class SecurityController extends AppController {
    private UserRepository $userRepository;

    public function __construct() {
        $this->userRepository = new UserRepository();
    }

    public function login() {
        if (session_status() === PHP_SESSION_NONE) {
            session_start();
        }

        // If the user is already logged in, throw him to the dashboard
        if (isset($_SESSION['user_id'])) {
            header("Location: /dashboard");
            exit();
        }

        if (!$this->isPost()) {
            return $this->render('login');
        }

        $email = $_POST['email'];
        $password = $_POST['password'];

        $user = $this->userRepository->getUser($email);

        // Verification: does the user exist and does the password match the hash in the database?
        if (!$user || !password_verify($password, $user->getPassword())) {
            $_SESSION['error_message'] = "Invalid credentials!";
            header("Location: /login");
            exit();
        }

        // We retrieve user details with a separate query
        $details = $this->userRepository->getUserDetails($user->getId());
        $avatar = ($details && !empty($details['avatar'])) ? $details['avatar'] : 'gaming-console.jpg';

        // Protection against Session Fixation
        session_regenerate_id(true);
        
        $_SESSION['user_id'] = $user->getId();
        $_SESSION['user_role'] = $user->getRole();
        $_SESSION['username'] = $user->getUsername();
        $_SESSION['user_avatar'] = $avatar;

        header("Location: /dashboard");
        exit();
    }

    public function register() {
        if (!$this->isPost()) {
            return $this->render('register');
        }

        $email = $_POST['email'];
        $password = $_POST['password'];
        $username = $_POST['username'];

        // Validation (for now basic, can be expanded)
        if (empty($email) || empty($password) || empty($username)) {
            return $this->render('register', ['messages' => ['All fields are required!']]);
        }

        // Hashing the password using the built-in function (also generates salt)
        $hashedPassword = password_hash($password, PASSWORD_BCRYPT);

        $user = new User(
            $email, 
            password_hash($password, PASSWORD_DEFAULT), 
            $username, 
            'USER', 
            0 // temporary ID, will be auto-generated by the database
        );
        
        try {
            $this->userRepository->addUser($user);
            $_SESSION['success_message'] = "Account created! You can now log in.";
            header("Location: /login");
            exit();
        } catch (Exception $e) {
            $_SESSION['error_message'] = "Email or username already exists!";
            header("Location: /register");
            exit();
        }
    }

    public function logout() {
        session_unset();
        session_destroy();
        header("Location: /");
        exit();
    }
}